Relocate the portage tree into /var/portage/tree and adjust accordingly.

diff --git a/lxc-gentoo b/lxc-gentoo
--- a/lxc-gentoo
+++ b/lxc-gentoo
@@ -184,6 +184,26 @@ write_distro_inittab() {
 
 setup_portage()
 {
+	# do a primitive portage setup
+	mkdir -p "$ROOTFS/etc/portage" && \
+	mkdir -p "$ROOTFS/var/portage/tree" && \
+	mkdir -p "$ROOTFS/var/portage/distfiles" \
+		|| die 2 "Error: unable to create needed portage directories.\n"
+
+	# relocate profile symlink
+	local src="$ROOTFS/etc/portage/make.profile"
+	local dest="$(readlink "$src")"
+	dest="${dest##*../}"
+	dest="${dest//usr\/portage/var/portage/tree}"
+	dest="$ROOTFS/$dest"
+	ln -f -s -r "$dest" "$src" \
+		|| die 2 "Error: unable to relocate portage symlink:\n%s -> %s\n" "$src" "$dest"
+
+	cat <<- EOF >> "$ROOTFS/etc/portage/make.conf"
+	PORTDIR="/var/portage/tree"
+	DISTDIR="/var/portage/distfiles"
+	EOF
+
 	if [[ "$PORTAGE_SOURCE" == "none" ]]; then
 		printf "Skipping portage tree setup\n"
 	else
@@ -195,8 +215,8 @@ setup_portage()
 
 		# PORTAGE_SOURCE will be set by fetch_portage.
 		if [[ -f "$PORTAGE_SOURCE" ]]; then
-			printf "Extracting the portage tree into %s/usr/portage...\n" "$ROOTFS"
-			tar -xpf "$PORTAGE_SOURCE" -C "$ROOTFS/usr/" \
+			printf "Extracting the portage tree into %s/var/portage/tree...\n" "$ROOTFS"
+			tar -xp --strip-components 1 -C "$ROOTFS/var/portage/tree/" -f "$PORTAGE_SOURCE" \
 				|| die 2 "Error: unable to extract the portage tree.\n"
 		else
 			printf "Warning: I don't know what to do with this portage source (%s)\n" "$PORTAGE_SOURCE"
