Add GPG setup instructions and the means to disable signature checking.

diff --git a/lxc-gentoo b/lxc-gentoo
--- a/lxc-gentoo
+++ b/lxc-gentoo
@@ -57,6 +57,9 @@ CONFFILE="$CONFFILE"
 MIRROR="${MIRROR:-http://distfiles.gentoo.org}"
 STAGE3_TARBALL="${STAGE3_TARBALL}"
 PORTAGE_SOURCE="$PORTAGE_SOURCE"
+if [[ ! -v PGP_DIR ]]; then
+	PGP_DIR="$HOME/.gnupg"
+fi
 
 # These paths are within the container so do not need to obey configure prefixes
 INITTAB="/etc/inittab"
@@ -491,16 +494,17 @@ verify_image()
 	local image_file="${image_file_absolute##*/}"
 	local image_dir="${image_file_absolute%/*}"
 
-	# verify it
-	command -v gpg > /dev/null \
-		|| die 2 "gpg program is not installed, unable to verify digest.\n"
+	if [[ -n "$PGP_DIR" && -d "$PGP_DIR" && -f "$PGP_DIR/pubring.gpg" ]]; then
+		# verify it
+		command -v gpg > /dev/null \
+			|| die 2 "gpg program is not installed, unable to verify digest.\n"
 
-	gpg --verify "$digest_file" \
-		|| die 7 "Error: Unable to verify PGP signature!\n%s\n%s\n%s\n%s\n"\
-		         "       ensure that you have imported the PGP key used to sign images"\
-		         "       the keys can be found at: http://www.gentoo.org/proj/en/releng/index.xml"\
-		         "       at the time of this writing, the key's fingerprint is"\
-		         "       13EB BDBE DE7A 1277 5DFD  B1BA BB57 2E0E 2D18 2910"
+		gpg --homedir "$PGP_DIR" --verify "$digest_file" \
+			|| die 7 "Error: Unable to verify PGP signature! Please refer to README, section PGP setup\n"
+	else
+		printf "Warning: \$PGP_DIR is empty or not a directory or $PGP_DIR/pubring.gpg\n%s\n" \
+		       "doesen't exist, disabling signature checking!"
+	fi
 
 	# verify sha512 checksum
 	command -v sha512sum > /dev/null \
