Refactor the copying (sigh) phase

diff --git a/lxc-gentoo b/lxc-gentoo
--- a/lxc-gentoo
+++ b/lxc-gentoo
@@ -526,19 +526,19 @@ create() {
 	fi
 
 	# check if the rootfs already exists
-	if [ ! -e "${ROOTFS}" ]; then
-		# make a local copy of the mini
-		echo -n "Copying filesystem from ${TEMPLATE} to ${ROOTFS}..."
-		cp -a "${TEMPLATE}" ${ROOTFS}
-		if [ ! $? -eq 0 ]; then
-			echo "FAILED."
-			return 1
-		else
-			echo "done."
-		fi
-	else
+	if [ -e "${ROOTFS}" ]; then
 		echo "ERROR: ${ROOTFS} already exists!"
 		return 1
+	fi
+	
+	# make a local copy of the mini
+	echo -n "Copying filesystem from ${TEMPLATE} to ${ROOTFS}..."
+	cp -a "${TEMPLATE}" ${ROOTFS}
+	if [ ! $? -eq 0 ]; then
+		echo "FAILED."
+		return 1
+	else
+		echo "done."
 	fi
 
 	write_lxc_configuration
